#!/bin/bash

yay -Fy
yay -Syu --noconfirm
yay -Yc --noconfirm

flatpak update -y
flatpak remove --unused -y

echo "updating plocate db"
sudo updatedb

sudo fwupdmgr refresh
sudo fwupdmgr update

sudo pacdiff
