#!/bin/sh

cd ~

# nvidia
export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1

# config
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

# vars
#export XDG_CURRENT_DESKTOP=Hyprland
#export XDG_SESSION_TYPE=wayland
#export XDG_SESSION_DESKTOP=Hyprland

# themeing
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

exec Hyprland
